common: &default_settings
  client_id: <%= ENV['GITHUB_CLIENT_ID'] %>
  secret: <%= ENV['GITHUB_CLIENT_SECRET'] %>

test:
  <<: *default_settings

development:
  <<: *default_settings

production:
  <<: *default_settings
